@dominio = http://localhost:3000

###OBTENER TODOS LOS PRODUCTOS
GET {{dominio}}/api/v1/productos
Accept: application/json

###CREAR UN NUEVO PRODUCTO
POST {{dominio}}/api/v1/productos
Content-Type: application/json

{
    "viaje": "Barcelona",
    "precio": 450,
    "fecha Ida": "05/02/2026",
    "fecha vuelta":"10/02/2026"
}

###OBTENER PRODUCTO POR ID
GET {{dominio}}/api/v1/productos/68fe5e05fe9f8cec1ae1f5a1
Accept: application/json

###ACTUALIZAR PRODUCTO POR ID
PUT {{dominio}}/api/v1/productos/68fe5e05fe9f8cec1ae1f5a3
Content-Type: application/json

{
    "viaje": "Asturias",
    "precio": 500,
    "fecha ida":"02/07/2026",
    "fecha vuelta":"09/07/2026"
}

###ELIMINAR PRODUCTO POR ID
DELETE {{dominio}}/api/v1/productos/68fe5e05fe9f8cec1ae1f5a4
